# Compiler settings - Can change to clang++ if preferred
CXX = g++
CXXFLAGS = -std=c++11 -Wall -pthread -g

# Build targets
TARGET = threadpool
SRC = thread-pool.cc Semaphore.cc main.cc

# Link the target with object files
$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Clean up build artifacts
clean:
	rm -f $(TARGET) $(OBJ)

.PHONY: all clean

tptest:
	$(CXX) $(CXXFLAGS) -o tptest tptest.cc thread-pool.cc Semaphore.cc

tpcustomtest:
	$(CXX) $(CXXFLAGS) -o tpcustomtest tpcustomtest.cc thread-pool.cc Semaphore.cc
